services:
    bitbag_sylius_wishlist_plugin.resolver.shop_user_wishlist_resolver:
        class: BitBag\SyliusWishlistPlugin\Resolver\ShopUserWishlistResolver
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist"
            - "@sylius.context.channel"

    bitbag_sylius_wishlist_plugin.resolver.wishlists_resolver:
        class: BitBag\SyliusWishlistPlugin\Resolver\WishlistsResolver
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@security.token_storage"
            - "@bitbag_sylius_wishlist_plugin.resolver.wishlist_cookie_token_resolver"
            - "@sylius.context.channel"
            - "@sylius.command_bus"
            - "@bitbag_sylius_wishlist_plugin.resolver.token_user_resolver"

    bitbag_sylius_wishlist_plugin.resolver.wishlist_cookie_token_resolver:
        class: BitBag\SyliusWishlistPlugin\Resolver\WishlistCookieTokenResolver
        arguments:
            - "@request_stack"
            - "%bitbag_sylius_wishlist_plugin.parameters.wishlist_cookie_token%"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@security.token_storage"
            - "@sylius.context.channel"

    bitbag_sylius_wishlist_plugin.resolver.token_user_resolver:
        class: BitBag\SyliusWishlistPlugin\Resolver\TokenUserResolver
