bitbag_sylius_wishlist_plugin_shop_wishlist_list_products:
    path: /wishlist
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.list_wishlist_products

bitbag_sylius_wishlist_plugin_shop_wishlist_add_products:
    path: /wishlist/add/products/all
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_products_to_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_add_product:
    path: /wishlist/add/{productId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_product_to_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_product:
    path: /wishlist/remove/{productId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.remove_product_from_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_selected_products:
    path: /wishlist/remove/products/selected
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.remove_selected_products_from_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_add_product_variant:
    path: /wishlist/add/variant/{variantId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_product_variant_to_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_add_selected_products:
    path: /wishlist/add/products/selected
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_selected_products_to_cart

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_product_variant:
    path: /wishlist/remove/variant/{variantId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.remove_product_variant_from_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_render_header_template:
    path: /wishlist/header-template
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.render_header_template
