bitbag_sylius_wishlist_plugin_shop_wishlist_list_products:
    path: /wishlist
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.list_wishlist_products

bitbag_sylius_wishlist_plugin_shop_wishlist_add_products:
    path: /wishlist/products
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_products_to_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_add_product:
    path: /wishlist/add/{productId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_product_to_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_product:
    path: /wishlist/remove/{productId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.remove_product_from_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_selected_products:
    path: /wishlist/products/delete
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.remove_selected_products_from_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_add_product_variant:
    path: /wishlist/add/variant/{variantId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_product_variant_to_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_add_selected_products:
    path: /wishlist/products/add
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.add_selected_products_to_cart

bitbag_sylius_wishlist_plugin_shop_wishlsit_export_selected_products_to_csv:
    path: /wishlist/csv/export
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.export_selected_products_to_csv

bitbag_sylius_wishlist_plugin_shop_wishlist_import_from_csv:
    path: /wishlist/csv/import
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.import_from_csv

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_product_variant:
    path: /wishlist/remove/variant/{variantId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.remove_product_variant_from_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_render_header_template:
    path: /wishlist/header-template
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.render_header_template

bitbag_sylius_wishlist_plugin_shop_wishlist_export_to_pdf:
    path: /wishlist/export/pdf
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.export_wishlist_to_pdf_action

bitbag_sylius_wishlist_plugin_shop_wishlist_clean:
    path: /wishlist/clear/{wishlistId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.clean_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_create_new_wishlist:
    path: /createWishlist
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.create_new_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_list_wishlists:
    path: /wishlists
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.list_wishlists

bitbag_sylius_wishlist_plugin_shop_wishlist_show_chosen_wishlist:
    path: /wishlist/{wishlistId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.show_chosen_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_remove_wishlist:
    path: /wishlists/{wishlistId}
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.remove_wishlist

bitbag_sylius_wishlist_plugin_shop_wishlist_edit_wishlist_name:
    path: /wishlists/{wishlistId}/edit
    defaults:
        _controller: bitbag_sylius_wishlist_plugin.controller.action.edit_wishlist_name
