services:
    bitbag_sylius_wishlist_plugin.controller.action.add_product_to_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddProductToWishlistAction
        arguments:
            - "@sylius.repository.product"
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist_product"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
            - "%wishlist_cookie_id%"

    bitbag_sylius_wishlist_plugin.controller.action.remove_product_from_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RemoveProductFromWishlistAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@sylius.repository.product"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist_product"
            - "@session.flash_bag"
            - "@translator"
            - "@router"

    bitbag_sylius_wishlist_plugin.controller.action.list_wishlist_products:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ListWishlistProductsAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@sylius.context.cart"
            - "@sylius.factory.order_item"
            - "@sylius.order_item_quantity_modifier"
            - "@form.factory"
            - "@sylius.order_modifier"
            - "@sylius.manager.order"
            - "@session.flash_bag"
            - "@templating.engine.twig"

    bitbag_sylius_wishlist_plugin.controller.action.render_header_template:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RenderHeaderTemplateAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@templating.engine.twig"

    bitbag_sylius_wishlist_plugin.context.wishlist:
        class: BitBag\SyliusWishlistPlugin\Context\WishlistContext
        arguments:
            - "@security.token_storage"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist"
            - "%wishlist_cookie_id%"

    bitbag_sylius_wishlist_plugin.custom_factory.wishlist:
        class: BitBag\SyliusWishlistPlugin\Factory\WishlistFactory
        decorates: bitbag_sylius_wishlist_plugin.factory.wishlist
        public: false
        arguments:
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist.inner"

    bitbag_sylius_wishlist_plugin.custom_factory.wishlist_product:
        class: BitBag\SyliusWishlistPlugin\Factory\WishlistProductFactory
        decorates: bitbag_sylius_wishlist_plugin.factory.wishlist_product
        public: false
        arguments:
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist_product.inner"

    bitbag_sylius_wishlist_plugin.event_listener.merge_user_wishlist_items:
        class: BitBag\SyliusWishlistPlugin\EventListener\MergeUserWishlistItemsListener
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist"
            - "%wishlist_cookie_id%"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    bitbag_sylius_wishlist_plugin.form.type.add_products_to_cart:
        class: BitBag\SyliusWishlistPlugin\Form\Type\AddProductsToCartType
        arguments:
            - "@sylius.factory.add_to_cart_command"
        tags:
            - { name: form.type }
