imports:
    - { resource: "services/**/*.yml" }

services:
    bitbag_sylius_wishlist_plugin.controller.action.base_wishlist_products_action:
        abstract: true
        class: BitBag\SyliusWishlistPlugin\Controller\Action\BaseWishlistProductsAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@sylius.context.cart"
            - "@form.factory"
            - "@session.flash_bag"
            - "@bitbag_sylius_wishlist_plugin.processor.wishlist_command_processor"
            - "@sylius.command_bus"
            - "@router"

    bitbag_sylius_wishlist_plugin.controller.action.add_product_to_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddProductToWishlistAction
        arguments:
            - "@security.token_storage"
            - "@sylius.repository.product"
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist_product"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
            - "%wishlist_cookie_token%"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.remove_product_from_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RemoveProductFromWishlistAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@sylius.repository.product"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist_product"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.add_product_variant_to_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddProductVariantToWishlistAction
        arguments:
            - "@security.token_storage"
            - "@sylius.repository.product_variant"
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist_product"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
            - "%wishlist_cookie_token%"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.remove_product_variant_from_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RemoveProductVariantFromWishlistAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@sylius.repository.product_variant"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist_product"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.remove_selected_products_from_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RemoveSelectedProductsFromWishlistAction
        parent: "bitbag_sylius_wishlist_plugin.controller.action.base_wishlist_products_action"
        public: true
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.add_selected_products_to_cart:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddSelectedProductsToCartAction
        parent: "bitbag_sylius_wishlist_plugin.controller.action.base_wishlist_products_action"
        public: true
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.list_wishlist_products:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ListWishlistProductsAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@sylius.context.cart"
            - "@form.factory"
            - "@twig"
            - "@bitbag_sylius_wishlist_plugin.processor.wishlist_command_processor"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.add_products_to_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddProductsToWishlistAction
        parent: "bitbag_sylius_wishlist_plugin.controller.action.base_wishlist_products_action"
        public: true
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.render_header_template:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RenderHeaderTemplateAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@twig"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.context.wishlist:
        class: BitBag\SyliusWishlistPlugin\Context\WishlistContext
        public: true
        arguments:
            - "@security.token_storage"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist"
            - "%wishlist_cookie_token%"

    bitbag_sylius_wishlist_plugin.custom_factory.wishlist:
        class: BitBag\SyliusWishlistPlugin\Factory\WishlistFactory
        decorates: bitbag_sylius_wishlist_plugin.factory.wishlist
        public: false
        arguments:
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist.inner"

    bitbag_sylius_wishlist_plugin.custom_factory.wishlist_product:
        class: BitBag\SyliusWishlistPlugin\Factory\WishlistProductFactory
        decorates: bitbag_sylius_wishlist_plugin.factory.wishlist_product
        public: false
        arguments:
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist_product.inner"

    bitbag_sylius_wishlist_plugin.event_listener.merge_user_wishlist_items:
        class: BitBag\SyliusWishlistPlugin\EventListener\MergeUserWishlistItemsListener
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist"
            - "%wishlist_cookie_token%"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    bitbag_sylius_wishlist_plugin.event_listener.clear_cookie_wishlist_items:
        class: BitBag\SyliusWishlistPlugin\EventListener\ClearCookieWishlistItemsListener
        arguments:
            - "@sylius.storage.cookie"
            - "%wishlist_cookie_token%"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    bitbag_sylius_wishlist_plugin.form.type.add_products_to_cart:
        class: BitBag\SyliusWishlistPlugin\Form\Type\AddProductsToCartType
        arguments:
            - "@sylius.factory.add_to_cart_command"
            - "@sylius.factory.order_item"
            - "@sylius.order_item_quantity_modifier"
            - "%sylius.form.type.cart_item.validation_groups%"
        tags:
            - { name: form.type }

    bitbag_sylius_wishlist_plugin.form.type.extension.add_to_cart_type_extension:
        class: BitBag\SyliusWishlistPlugin\Form\Extension\AddToCartTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Order\AddToCartType }

    bitbag_sylius_wishlist_plugin.controller.action.export_wishlist_to_pdf_action:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ExportWishlistToPdfAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@sylius.context.cart"
            - "@form.factory"
            - "@session.flash_bag"
            - "@translator"
            - "@sylius.repository.product_variant"
            - "@router"
            - "@sylius.manager.order"
            - "@twig"
            - "@sylius.context.channel"
            - "@bitbag_sylius_wishlist_plugin.resolver.variant.image.path.resolver"
            - "@bitbag_sylius_wishlist_plugin.model.resolver.variant.pdf.model.factory"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.resolver.variant.image.path.resolver:
        class: BitBag\SyliusWishlistPlugin\Resolver\VariantImagePathResolver

    bitbag_sylius_wishlist_plugin.model.resolver.variant.pdf.model.factory:
        class: BitBag\SyliusWishlistPlugin\Model\Factory\VariantPdfModelFactory