imports:
    - { resource: "services/**/*.yml" }

services:
    bitbag_sylius_wishlist_plugin.controller.action.base_wishlist_products_action:
        abstract: true
        class: BitBag\SyliusWishlistPlugin\Controller\Action\BaseWishlistProductsAction
        arguments:
            - "@sylius.context.cart"
            - "@form.factory"
            - "@session.flash_bag"
            - "@bitbag_sylius_wishlist_plugin.processor.wishlist_command_processor"
            - "@sylius.command_bus"
            - "@router"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"

    bitbag_sylius_wishlist_plugin.controller.action.base_wishlists_listing_action:
        abstract: true
        class: BitBag\SyliusWishlistPlugin\Controller\Action\BaseWishlistsListingAction
        arguments:
            - "@twig"
            - "@bitbag_sylius_wishlist_plugin.resolver.wishlists_resolver"

    bitbag_sylius_wishlist_plugin.controller.action.list_wishlists:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ListWishlistsAction
        parent: "bitbag_sylius_wishlist_plugin.controller.action.base_wishlists_listing_action"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.render_header_template:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RenderHeaderTemplateAction
        parent: "bitbag_sylius_wishlist_plugin.controller.action.base_wishlists_listing_action"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.add_product_to_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddProductToWishlistAction
        arguments:
            - "@sylius.repository.product"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist_product"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
            - "@bitbag_sylius_wishlist_plugin.resolver.wishlists_resolver"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.remove_product_from_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RemoveProductFromWishlistAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.context.wishlist"
            - "@sylius.repository.product"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist_product"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.clean_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\CleanWishlistAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist_product"
            - '@session.flash_bag'
            - '@translator'
            - '@router'
        tags:
            - { name: controller.service_arguments }


    bitbag_sylius_wishlist_plugin.controller.action.add_product_variant_to_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddProductVariantToWishlistAction
        arguments:
            - "@sylius.repository.product_variant"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist_product"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.remove_product_variant_from_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RemoveProductVariantFromWishlistAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@sylius.repository.product_variant"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist_product"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.remove_selected_products_from_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\RemoveSelectedProductsFromWishlistAction
        parent: "bitbag_sylius_wishlist_plugin.controller.action.base_wishlist_products_action"
        public: true
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.add_selected_products_to_cart:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddSelectedProductsToCartAction
        parent: "bitbag_sylius_wishlist_plugin.controller.action.base_wishlist_products_action"
        public: true
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.export_selected_products_to_csv:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ExportSelectedProductsToCsvAction
        arguments:
            - '@sylius.context.cart.new_shop_based.inner'
            - '@form.factory'
            - '@session.flash_bag'
            - "@sylius.command_bus"
            - "@bitbag_sylius_wishlist_plugin.processor.wishlist_command_processor"
            - "@router"
            - "@translator"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.import_from_csv:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ImportWishlistFromCsvAction
        arguments:
            - "@form.factory"
            - '@session.flash_bag'
            - "@sylius.command_bus"
            - "@twig"
            - "@bitbag_sylius_wishlist_plugin.resolver.wishlists_resolver"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.list_wishlist_products:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ListWishlistProductsAction
        arguments:
            - "@sylius.context.cart"
            - "@form.factory"
            - "@twig"
            - "@bitbag_sylius_wishlist_plugin.processor.wishlist_command_processor"
            - "@bitbag_sylius_wishlist_plugin.resolver.wishlists_resolver"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.add_products_to_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddProductsToCartAction
        parent: "bitbag_sylius_wishlist_plugin.controller.action.base_wishlist_products_action"
        public: true
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.context.wishlist:
        class: BitBag\SyliusWishlistPlugin\Context\WishlistContext
        public: true
        arguments:
            - "@security.token_storage"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist"
            - "%bitbag_sylius_wishlist_plugin.parameters.wishlist_cookie_token%"

    bitbag_sylius_wishlist_plugin.custom_factory.wishlist:
        class: BitBag\SyliusWishlistPlugin\Factory\WishlistFactory
        decorates: bitbag_sylius_wishlist_plugin.factory.wishlist
        public: false
        arguments:
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist.inner"

    bitbag_sylius_wishlist_plugin.custom_factory.wishlist_product:
        class: BitBag\SyliusWishlistPlugin\Factory\WishlistProductFactory
        decorates: bitbag_sylius_wishlist_plugin.factory.wishlist_product
        public: false
        arguments:
            - "@bitbag_sylius_wishlist_plugin.custom_factory.wishlist_product.inner"

    bitbag_sylius_wishlist_plugin.custom_factory.csv_wishlist_product:
        class: BitBag\SyliusWishlistPlugin\Factory\CsvWishlistProductFactory

    bitbag_sylius_wishlist_plugin.custom_factory.csv.serializer:
        class: BitBag\SyliusWishlistPlugin\Factory\CsvSerializerFactory

    bitbag_sylius_wishlist_plugin.custom_factory.dom_pdf:
        class: BitBag\SyliusWishlistPlugin\Factory\DomPdfFactory
        arguments:
            - "@bitbag_sylius_wishlist_plugin.custom_factory.dom_pdf_options"

    bitbag_sylius_wishlist_plugin.custom_factory.dom_pdf_options:
        class: BitBag\SyliusWishlistPlugin\Factory\DomPdfOptionsFactory

    bitbag_sylius_wishlist_plugin.event_listener.create_new_wishlist:
        class: BitBag\SyliusWishlistPlugin\EventSubscriber\CreateNewWishlistSubscriber
        arguments:
            - "%bitbag_sylius_wishlist_plugin.parameters.wishlist_cookie_token%"
            - "@bitbag_sylius_wishlist_plugin.resolver.wishlists_resolver"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@security.token_storage"
        tags:
            - { name: kernel.event_subscriber }

    bitbag_sylius_wishlist_plugin.form.type.add_products_to_cart:
        class: BitBag\SyliusWishlistPlugin\Form\Type\AddProductsToCartType
        arguments:
            - "@sylius.factory.add_to_cart_command"
            - "@sylius.factory.order_item"
            - "@sylius.order_item_quantity_modifier"
            - "%sylius.form.type.cart_item.validation_groups%"
        tags:
            - { name: form.type }

    bitbag_sylius_wishlist_plugin.form.type.extension.add_to_cart_type_extension:
        class: BitBag\SyliusWishlistPlugin\Form\Extension\AddToCartTypeExtension
        arguments:
            - "@bitbag_sylius_wishlist_plugin.resolver.wishlists_resolver"
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Order\AddToCartType }

    bitbag_sylius_wishlist_plugin.controller.action.export_wishlist_to_pdf_action:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ExportWishlistToPdfAction
        parent: "bitbag_sylius_wishlist_plugin.controller.action.base_wishlist_products_action"
        public: true
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.resolver.variant_image_path_resolver:
        class: BitBag\SyliusWishlistPlugin\Resolver\VariantImageToDataUriResolver
        arguments:
            - "@bitbag_sylius_wishlist_plugin.resolver.generate_data_uri_for_image_resolver"

    bitbag_sylius_wishlist_plugin.resolver.generate_data_uri_for_image_resolver:
        class: BitBag\SyliusWishlistPlugin\Resolver\GenerateDataUriForImageResolver
        arguments:
            - "@assets._package_shop"
            - "@liip_imagine.service.filter"
            - "sylius_shop_product_thumbnail"

    bitbag_sylius_wishlist_plugin.services.generator.model_creator:
        class: BitBag\SyliusWishlistPlugin\Services\Generator\ModelCreator
        arguments:
            - "@bitbag_sylius_wishlist_plugin.resolver.variant_image_path_resolver"
            - "@bitbag_sylius_wishlist_plugin.model.factory.variant_pdf_model_factory"
            - "@request_stack"

    bitbag_sylius_wishlist_plugin.model.factory.variant_pdf_model_factory:
        class: BitBag\SyliusWishlistPlugin\Model\Factory\VariantPdfModelFactory

    bitbag_sylius_wishlist_plugin.services.exporter:
        class: BitBag\SyliusWishlistPlugin\Services\Exporter\WishlistToPdfExporter
        arguments:
            - "@bitbag_sylius_wishlist_plugin.processor.variant_pdf_model_processor"
            - "@bitbag_sylius_wishlist_plugin.services.exporter.dom_pdf_wishlist_exporter"

    bitbag_sylius_wishlist_plugin.services.exporter.dom_pdf_wishlist_exporter:
        class: BitBag\SyliusWishlistPlugin\Services\Exporter\DomPdfWishlistExporter
        arguments:
            - "@twig"
            - "@bitbag_sylius_wishlist_plugin.custom_factory.dom_pdf"

    bitbag_sylius_wishlist_plugin.controller.action.create_new_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\CreateNewWishlistAction
        arguments:
            - "@form.factory"
            - "@sylius.command_bus"
            - "@twig"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.form.type.create_new_wishlist:
        class: BitBag\SyliusWishlistPlugin\Form\Type\CreateNewWishlistType
        arguments:
        tags:
            - { name: form.type }

    bitbag_sylius_wishlist_plugin.form.type.wishlist_collection_type:
        class: BitBag\SyliusWishlistPlugin\Form\Type\WishlistCollectionType
        arguments:
            - "@translator"
            - "@bitbag_sylius_wishlist_plugin.processor.selected_wishlist_products_processor"
        tags:
            - { name: form.type }

    bitbag_sylius_wishlist_plugin.controller.action.show_chosen_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\ShowChosenWishlistAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@sylius.context.cart"
            - "@form.factory"
            - "@twig"
            - "@bitbag_sylius_wishlist_plugin.processor.wishlist_command_processor"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.add_product_to_selected_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\AddProductToSelectedWishlistAction
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@sylius.repository.product"
            - "@session.flash_bag"
            - "@translator"
            - "@router"
            - "@sylius.command_bus"
        tags:
            - { name: controller.service_arguments }

    bitbag_sylius_wishlist_plugin.controller.action.copy_selected_products_to_other_wishlist:
        class: BitBag\SyliusWishlistPlugin\Controller\Action\CopySelectedProductsToOtherWishlistAction
        arguments:
            - "@sylius.context.cart"
            - "@form.factory"
            - "@session.flash_bag"
            - "@sylius.command_bus"
            - "@bitbag_sylius_wishlist_plugin.processor.wishlist_command_processor"
            - "@router"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
        tags:
            - { name: controller.service_arguments }


    bitbag_sylius_wishlist_plugin.twig.extension.wishlist_extension:
        class: BitBag\SyliusWishlistPlugin\Twig\WishlistExtension
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.resolver.wishlist_cookie_token_resolver"
        tags:
            - { name: twig.extension }
